### ISSUE TITLE
exponent.cpp is calling me a dickhead

### ISSUE THREAD

**Issue by umute97** [martin2250/Programmieren-fuer-Physiker#1]
Hello Martin,

I tried to use your code to calculate exp(x), because my calculator is broken.

When I try to execute the program after compiling it and enter an argument greater than 2, the program calls me a dickhead.

As this couldn't possibly be intended by you, you should probably revise your code again.

And I spotted a small amount of gayness in your code in Line 6:
`using namespace std;`

Everyone knows that using namespaces in C++ is a sign of the weak, please fix.

Yours sincerely,

hodenkobold69
M.o.U.

**Comment by martin2250** [comment]
Hello @hodenkobold69,

despite my best efforts, I failed to reproduce your issue:
```
./exponent 3
20.085537
```
or, reading the input from stdin:
```
./exponent <<< "3\n"
enter x: exp(3) = 20.085537
```
both times using an argument (3) that is evidently grater than 2 [[citation](http://www.wolframalpha.com/input/?i=3+%3E+2)].


Concerning you taking offence in my usage of the 'using' keyword, I can only encourage you to propose a better, more elegant solution as a pull request and I will consider actually giving a shit.

Dickhead.
